services:
    akeneo_connectivity.connection.persistence.query.are_credentials_valid_combination:
        class: Akeneo\Connectivity\Connection\Infrastructure\WrongCredentialsConnection\Persistence\Dbal\DbalAreCredentialsValidCombinationQuery
        arguments:
            - '@database_connection'

    akeneo_connectivity.connection.persistence.query.select_connection_code_by_client_id:
        class: Akeneo\Connectivity\Connection\Infrastructure\WrongCredentialsConnection\Persistence\Dbal\DbalSelectConnectionCodeByClientIdQuery
        arguments:
            - '@database_connection'

    akeneo_connectivity.connection.persistence.repository.wrong_credentials_combination:
        class: Akeneo\Connectivity\Connection\Infrastructure\WrongCredentialsConnection\Persistence\Dbal\DbalWrongCredentialsCombinationRepository
        arguments:
            - '@database_connection'

    akeneo_connectivity.connection.api_connection_subscriber:
        class: Akeneo\Connectivity\Connection\Infrastructure\WrongCredentialsConnection\ApiAuthenticationEventSubscriber
        arguments:
            - '@akeneo_connectivity.connection.persistence.query.are_credentials_valid_combination'
            - '@akeneo_connectivity.connection.persistence.query.select_connection_code_by_client_id'
            - '@akeneo_connectivity.connection.persistence.repository.wrong_credentials_combination'
        tags:
            - { name: kernel.event_subscriber }
